# Generated by Django 5.1.1 on 2024-12-03 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_app', '0003_teluser_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact', models.IntegerField(unique=True)),
                ('tg_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='example_app.teluser')),
            ],
        ),
    ]
