# Generated by Django 5.1.1 on 2024-12-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_app', '0007_remove_confirmchannel_tg_id_confirmchannel_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmchannel',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
