# Generated by Django 5.1.1 on 2024-12-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_app', '0011_product_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=2, upload_to='product_media/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProductMedia',
        ),
    ]
