# Generated by Django 5.1.1 on 2024-12-03 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example_app', '0013_productmedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
