# Generated by Django 5.1.1 on 2024-12-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_app', '0014_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='teluser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
